name: Production - Build & Push (prod)

permissions:
  contents: write

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "environments/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current time (KST)
        uses: josStorer/get-current-time@v2.1.2
        id: current_time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (prod)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            buyornot22/sseotdabwa-be:${{ steps.current_time.outputs.formattedTime }}

      - name: Update prod manifest image tag
        run: |
          sed -i "s|image: buyornot22/sseotdabwa-be:.*|image: buyornot22/sseotdabwa-be:${{ steps.current_time.outputs.formattedTime }}|g" environments/prod/deployment.yaml
          echo "Updated manifest image:"
          grep -n "image:" environments/prod/deployment.yaml

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add environments/prod/deployment.yaml
          git commit -m "deploy: (prod) ${{ steps.current_time.outputs.formattedTime }}" || echo "No changes to commit"
          git push origin main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
