apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buyornot-be
  namespace: buyornot-dev
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: dev.buy-or-not.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: buyornot-be
                port:
                  number: 80
